"""
Tag Models - AI-generated message tags and statistics

MessageTag: Many-to-many relationship between messages and tags
TagStats: Aggregated statistics for tag usage and trends
"""

from datetime import datetime
from typing import Optional

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Integer,
    Numeric,
    PrimaryKeyConstraint,
    String,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base


class MessageTag(Base):
    """
    AI-generated tags for messages (many-to-many relationship).

    Tags are generated by:
    - Ollama LLM (keywords, topics, entities)
    - Rule-based extraction (hashtags, mentions)
    - Manual tagging by analysts

    Tag types:
    - keyword: Single-word descriptors (e.g., "tank", "civilian")
    - topic: Broader categories (e.g., "military_operation", "humanitarian")
    - entity: Named entities (e.g., "Bakhmut", "47th Brigade")
    - emotion: Emotional tone (e.g., "fear", "hope", "anger")
    - urgency: Urgency indicators (e.g., "breaking", "developing")
    """

    __tablename__ = "message_tags"
    __table_args__ = (
        UniqueConstraint('message_id', 'tag', 'tag_type', name='uq_message_tag'),
    )

    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Foreign key to message
    message_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("messages.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Tag data
    tag: Mapped[str] = mapped_column(
        String(100), nullable=False, index=True
    )  # Tag text (lowercase, normalized)
    tag_type: Mapped[str] = mapped_column(
        String(50), nullable=False, index=True
    )  # 'keyword', 'topic', 'entity', 'emotion', 'urgency'

    # Confidence score (0.00-1.00)
    confidence: Mapped[Optional[float]] = mapped_column(
        Numeric(3, 2),
        CheckConstraint("confidence >= 0 AND confidence <= 1", name="tag_confidence_range"),
        nullable=True,
        index=True,
    )

    # Generation metadata
    generated_by: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # 'ollama:llama3.2', 'rule_based', 'manual'

    # Timestamp
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    message: Mapped["Message"] = relationship("Message", back_populates="tags")

    def __repr__(self) -> str:
        return f"<MessageTag(id={self.id}, message_id={self.message_id}, tag='{self.tag}', type='{self.tag_type}', confidence={self.confidence})>"


class TagStats(Base):
    """
    Aggregated statistics for tag usage and trends.

    Updated via database trigger whenever message_tags are inserted/updated.
    Provides quick lookups for:
    - Tag popularity (usage_count)
    - Tag quality (avg_confidence)
    - Tag lifecycle (first_seen, last_seen)
    - Trending analysis (recent usage vs historical)
    """

    __tablename__ = "tag_stats"
    __table_args__ = (
        PrimaryKeyConstraint('tag', 'tag_type', name='pk_tag_stats'),
    )

    # Composite primary key (tag + tag_type)
    tag: Mapped[str] = mapped_column(String(100), nullable=False)
    tag_type: Mapped[str] = mapped_column(String(50), nullable=False)

    # Usage statistics
    usage_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="1")
    avg_confidence: Mapped[Optional[float]] = mapped_column(
        Numeric(3, 2),
        CheckConstraint("avg_confidence >= 0 AND avg_confidence <= 1", name="avg_confidence_range"),
        nullable=True,
    )

    # Lifecycle timestamps
    first_seen: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    last_seen: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    def __repr__(self) -> str:
        return f"<TagStats(tag='{self.tag}', type='{self.tag_type}', usage={self.usage_count}, avg_confidence={self.avg_confidence})>"
